export const typeColorMap: Record<string, string> = {
    fire: "from-orange-500 to-red-600",
    water: "from-blue-400 to-blue-600",
    grass: "from-green-400 to-green-600",
    electric: "from-yellow-300 to-yellow-500",
    psychic: "from-pink-400 to-purple-600",
    ice: "from-cyan-200 to-blue-300",
    dragon: "from-indigo-500 to-purple-800",
    dark: "from-gray-700 to-black",
    fairy: "from-pink-300 to-pink-500",
    normal: "from-gray-300 to-gray-400",
    fighting: "from-red-700 to-red-900",
    poison: "from-purple-500 to-purple-900",
    ground: "from-yellow-600 to-yellow-800",
    flying: "from-indigo-300 to-indigo-500",
    bug: "from-lime-400 to-lime-600",
    rock: "from-stone-500 to-stone-700",
    ghost: "from-purple-800 to-indigo-950",
    steel: "from-slate-400 to-slate-600",
};

export const POKEMON_TYPES = [
    { value: "water", label: "Água" },
    { value: "steel", label: "Aço" },
    { value: "dragon", label: "Dragão" },
    { value: "electric", label: "Elétrico" },
    { value: "fairy", label: "Fada" },
    { value: "ghost", label: "Fantasma" },
    { value: "fire", label: "Fogo" },
    { value: "ice", label: "Gelo" },
    { value: "grass", label: "Grama" },
    { value: "bug", label: "Inseto" },
    { value: "fighting", label: "Lutador" },
    { value: "normal", label: "Normal" },
    { value: "rock", label: "Pedra" },
    { value: "psychic", label: "Psíquico" },
    { value: "dark", label: "Sombrio" },
    { value: "ground", label: "Terra" },
    { value: "poison", label: "Veneno" },
    { value: "flying", label: "Voador" },

];
